// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/xabi93/racers/internal/storage/postgres/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
