// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Race is the predicate function for race builders.
type Race func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
