// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// RacesColumns holds the columns for the "races" table.
	RacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
		{Name: "date", Type: field.TypeTime},
	}
	// RacesTable holds the schema information for the "races" table.
	RacesTable = &schema.Table{
		Name:        "races",
		Columns:     RacesColumns,
		PrimaryKey:  []*schema.Column{RacesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 2147483647},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:        "users",
		Columns:     UsersColumns,
		PrimaryKey:  []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RaceCompetitorsColumns holds the columns for the "race_competitors" table.
	RaceCompetitorsColumns = []*schema.Column{
		{Name: "race_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// RaceCompetitorsTable holds the schema information for the "race_competitors" table.
	RaceCompetitorsTable = &schema.Table{
		Name:       "race_competitors",
		Columns:    RaceCompetitorsColumns,
		PrimaryKey: []*schema.Column{RaceCompetitorsColumns[0], RaceCompetitorsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "race_competitors_race_id",
				Columns: []*schema.Column{RaceCompetitorsColumns[0]},

				RefColumns: []*schema.Column{RacesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:  "race_competitors_user_id",
				Columns: []*schema.Column{RaceCompetitorsColumns[1]},

				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RacesTable,
		UsersTable,
		RaceCompetitorsTable,
	}
)

func init() {
	RaceCompetitorsTable.ForeignKeys[0].RefTable = RacesTable
	RaceCompetitorsTable.ForeignKeys[1].RefTable = UsersTable
}
