// Code generated by entc, DO NOT EDIT.

package race

const (
	// Label holds the string label denoting the race type in the database.
	Label = "race"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"

	// EdgeCompetitors holds the string denoting the competitors edge name in mutations.
	EdgeCompetitors = "competitors"

	// Table holds the table name of the race in the database.
	Table = "races"
	// CompetitorsTable is the table the holds the competitors relation/edge. The primary key declared below.
	CompetitorsTable = "race_competitors"
	// CompetitorsInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CompetitorsInverseTable = "users"
)

// Columns holds all SQL columns for race fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDate,
}

var (
	// CompetitorsPrimaryKey and CompetitorsColumn2 are the table columns denoting the
	// primary key for the competitors relation (M2M).
	CompetitorsPrimaryKey = []string{"race_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
