// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/xabi93/racers/internal/storage/postgres/ent/race"
	"github.com/xabi93/racers/internal/storage/postgres/ent/user"
)

// RaceCreate is the builder for creating a Race entity.
type RaceCreate struct {
	config
	mutation *RaceMutation
	hooks    []Hook
}

// SetName sets the name field.
func (rc *RaceCreate) SetName(s string) *RaceCreate {
	rc.mutation.SetName(s)
	return rc
}

// SetDate sets the date field.
func (rc *RaceCreate) SetDate(t time.Time) *RaceCreate {
	rc.mutation.SetDate(t)
	return rc
}

// SetID sets the id field.
func (rc *RaceCreate) SetID(s string) *RaceCreate {
	rc.mutation.SetID(s)
	return rc
}

// AddCompetitorIDs adds the competitors edge to User by ids.
func (rc *RaceCreate) AddCompetitorIDs(ids ...string) *RaceCreate {
	rc.mutation.AddCompetitorIDs(ids...)
	return rc
}

// AddCompetitors adds the competitors edges to User.
func (rc *RaceCreate) AddCompetitors(u ...*User) *RaceCreate {
	ids := make([]string, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return rc.AddCompetitorIDs(ids...)
}

// Mutation returns the RaceMutation object of the builder.
func (rc *RaceCreate) Mutation() *RaceMutation {
	return rc.mutation
}

// Save creates the Race in the database.
func (rc *RaceCreate) Save(ctx context.Context) (*Race, error) {
	var (
		err  error
		node *Race
	)
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RaceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			node, err = rc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RaceCreate) SaveX(ctx context.Context) *Race {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (rc *RaceCreate) check() error {
	if _, ok := rc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := rc.mutation.Name(); ok {
		if err := race.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := rc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New("ent: missing required field \"date\"")}
	}
	return nil
}

func (rc *RaceCreate) sqlSave(ctx context.Context) (*Race, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}

func (rc *RaceCreate) createSpec() (*Race, *sqlgraph.CreateSpec) {
	var (
		_node = &Race{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: race.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: race.FieldID,
			},
		}
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: race.FieldName,
		})
		_node.Name = value
	}
	if value, ok := rc.mutation.Date(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: race.FieldDate,
		})
		_node.Date = value
	}
	if nodes := rc.mutation.CompetitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   race.CompetitorsTable,
			Columns: race.CompetitorsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RaceCreateBulk is the builder for creating a bulk of Race entities.
type RaceCreateBulk struct {
	config
	builders []*RaceCreate
}

// Save creates the Race entities in the database.
func (rcb *RaceCreateBulk) Save(ctx context.Context) ([]*Race, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Race, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (rcb *RaceCreateBulk) SaveX(ctx context.Context) []*Race {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
