// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"
)

type CreateRaceResult interface {
	IsCreateRaceResult()
}

type Error interface {
	IsError()
}

type RaceResult interface {
	IsRaceResult()
}

type InvalidDateError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (InvalidDateError) IsCreateRaceResult() {}
func (InvalidDateError) IsError()            {}

type InvalidNameError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (InvalidNameError) IsCreateRaceResult() {}
func (InvalidNameError) IsError()            {}

type RaceByIDNotFound struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	ID      string `json:"id"`
}

func (RaceByIDNotFound) IsRaceResult() {}
func (RaceByIDNotFound) IsError()      {}

type RaceInput struct {
	Name string    `json:"name"`
	Date time.Time `json:"date"`
}
